---
_hotel_id: HOT968
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
latitude: 44.30393
longitude: 9.21173
name: Hotel Piccolo Portofino
email: steffan@traveltripper.io
phone_number: "--"
address:
  street1: Via Duca degli Abruzzi 31
  street2: ''
  state: ''
  city: Portofino
  country: 
  zip_code: '16034'
